# Generated by Django 2.2.5 on 2019-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('user', models.CharField(max_length=64, verbose_name='用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
        ),
    ]
