# Generated by Django 2.2.5 on 2019-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190908_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
