# Generated by Django 2.2.5 on 2019-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190908_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='task',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
