# Generated by Django 2.2.5 on 2019-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190908_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
