# Generated by Django 2.2.5 on 2019-09-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_task_converted_imaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='converted_imaged',
            new_name='converted_image',
        ),
    ]
